### ISSUE TITLE
Power Supply Shuts Down On Current Spikes

### ISSUE THREAD

**Issue by dkt01** [dkt01/Swerve-Platform#4]
When modules suddenly change direction, the power supply shuts itself down and won't re-enable without disconnecting mains power for ~30 seconds.  Seems like a safety feature.  Need to contact manufacturer to see if there's a way to handle these transient spikes gracefully.

Model: MEAN WELL RSP-1500-12

**Comment by dkt01** [comment]
I don't see an easy way to disable the over current protection on the power supply, but there are a couple options.

On the software side, we can ramp all motor control so there is less starting current.  This may make the platform less responsive, but it may be acceptable at low speeds.

An electrical work around is to add a capacitor in parallel with the power supply to handle current spikes.  Large-capacity capacitors are common in car audio setups, but the one potential issue is they require special care to charge them prior to use.  We can possibly handle this with a voltage comparitor and a high-current relay.  The relay would connect the + side of the capacitor in parallel with the DC power supply only if the capacitor voltage is above a threshold (11.X V or so).  Another parallel wire between the power supply + and the capacitor + with an inline resistor would always be connected so the capacitor would safely charge at power on (and discharge at power off if we don't add an inline diode; discharge would be safest, but would increase startup time).
Possible additional parts:
* [2.2F Capacitor](https://www.amazon.com/BULLZ-AUDIO-Digital-Capacitor-BCAP2-2/dp/B009XUNNZW) ($40)- Not sure on size, but this seemed like a middle solution.  5F models are about $20 more
* [Splitter](https://www.amazon.com/LEIGESAUDIO-Copper-Gauge-Distribution-Splitter/dp/B09188MVP2) ($20)- For wiring parallel supplies
* [12V 200A Relay](https://www.amazon.com/Support-Relay-Truck-Marine-Charge/dp/B00WMBV05Y) ($15)- 200A is a bit overkill, but for safety factor
* [Voltage Comparator](https://www.amazon.com/Taidacent-Voltage-Comparator-Channel-Comparison/dp/B08K4NTTK8) ($20)- Detect when capacitor is charged to activate main power relay

**Comment by ngraves2** [comment]
Let’s see if software current ramp fixes it.

If that doesn’t work, then I would want to ensure we discharge the
capacitor for safety. I don’t think startup time is a concern.

Or we can look into a new power supply.
